Freeze urllib3 to version 1.23
After upgrade of urllib3 to version 1.24 the following error started
to appear breaking CRMint's functionality:

AttributeError: 'VerifiedHTTPSConnection' object has no attribute
'_tunnel_host'